version: "3.1"

services:
  nginx:
    image: nginx:1.23.3-alpine
    restart: always
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./.htpasswd:/etc/nginx/.htpasswd
      - ./ssl:/etc/nginx/ssl
      - ./www:/var/www
    ports:
      - 80:80
      - 443:443
      # - 7860:7860
      - 8000:8000
      - 8001:8001
      - 8002:8002
    networks:
      - nginx-network

networks:
  nginx-network:
    external: true
